name: Build toolchain

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build binutils
      run: |
        cd ${{ github.workspace }}
        cd toolchain/butils
        ./build.sh
    - name: build gcc
      run: |
        cd ${{ github.workspace }}
        cd toolchain/gcc
        ./build.sh
